<?xml version="1.0"?>
<package format="2">
  <name>amr_bringup</name>
  <version>0.0.1</version>
  <description>
    Top-level bringup and system launch files for the mecanum AMR.
  </description>

  <maintainer email="you@example.com">amr_user</maintainer>
  <license>BSD</license>

  <buildtool_depend>catkin</buildtool_depend>

  <exec_depend>roslaunch</exec_depend>
  <exec_depend>amr_description</exec_depend>
  <exec_depend>amr_teensy_bridge</exec_depend>
  <exec_depend>amr_sensors</exec_depend>
  <exec_depend>robot_localization</exec_depend>
  <exec_depend>rviz</exec_depend>

  <export>
  </export>
</package>

